services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_DEBUG=1
      - ALLOWED_HOSTS=*
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8001/api
    depends_on:
      - backend
    restart: always
